tasks:
- install:
    flavor: notcmalloc
    debuginfo: true
- ceph:
- rgw:
    client.0:
      valgrind: [--tool=memcheck]
- s3tests:
    client.0:
      force-branch: rgw-lifecycle-testing
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 5
